version: '3.6'

services:
  elasticsearch:
    container_name: elkp_es01
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #sample volumes
      - ./elasticsearch/volumes:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk-practice
  
  logstash:
    container_name: elkp_logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/pipeline.yml:/usr/share/logstash/config/pipeline.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      #sample data
      - ./sample:/var/tmp/log
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk-practice
    depends_on:
      - elasticsearch

  # kibana:
  #   container_name: sfilter_kibana
  #   image: docker.elastic.co/kibana/kibana:7.6.0
  #   volumes:
  #     - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
  #   ports:
  #     - 5601:5601
  #   networks:
  #     - elk-practice
  #   depends_on:
  #     - elasticsearch

networks:
  elk-practice:
    driver: bridge